### ISSUE TITLE
Scrolling on mobile device

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/ComplexViewer#113]
When scrolling on the complex portal and you tap on the CP-viewer you can't scroll you have to 'jump' over the viewer to continue scrolling.

**Comment by colin-combe** [comment]
ok, will have a look at why

**Comment by bmeldal** [comment]
It was also not opening the bar but opening UniProt on "tapping" the protein icon.

Different issue?

**Comment by colin-combe** [comment]
i'll look at it with this issue,
c

**Comment by bmeldal** [comment]
This appears to be an Android issue as it doesn't happen on Max's iphone.

**Comment by colin-combe** [comment]
Think both these issues are fixed in MICommunity:master branch now.
It will still only scroll page when it is the background that is touched, if it is an item/glyph in the display that is the start point then that thing will be moved within the viewer.

I'm closing because I think its fixed; reopen if I'm mistaken about that...
