### ISSUE TITLE
viewer breaks with complexes as participants

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#130]
Hi Colin, 

We have now released all yeast complexes but they contain complexes as participants, in some cases in 2 layers.

Any idea if and when the viewer will cope with it? At the moment it is an empty space, e.g.
https://www.ebi.ac.uk/complexportal/complex/CPX-1556

The complex symbol should be a hexagon.

Birgit

**Comment by bmeldal** [comment]
@noedelta This is what you just mentioned to me about the Jami-Json not pulling in the complex AC for participants, right? Can you reply directly?

**Comment by colin-combe** [comment]
Maybe just leave the #103 issue / leave the sub complexes in the JSON, and I'll see what I can do once the missing complex AC issue is fixed.
(Could make including / excluding sub-complexes an option)

**Comment by noedelta** [comment]
Hi @colin-combe I have the impression, as you discovered, that the mi-json will need to adapt to the complexes as participants. I will have a look as soon as I can and I will tell you. Thank you so much for doing the update of the viewer.

**Comment by colin-combe** [comment]
Hi,
with regards the new test file we added to the project (CPX-1556-B.json), the reason it doesn't work is because the newly added top-level complex has problems with the way it refers to features.

It looks like its closely related to the 'features on complexes' discussion topic at the PSI meeting.

As we have it at the moment, the sequenceData of a feature has, not just the position, but also the interactor_ref and participant_ref as required attributes (see https://github.com/MICommunity/ComplexViewer/blob/master/mi-json-schema.json#L655-L680). The viewer crashes because these are missing from a feature on a participant of the top-level complex (https://github.com/MICommunity/ComplexViewer/blob/master/demo/data/complex/CPX-1556-B.json#L688-L692).

I suppose the proposal from the meeting: 
> Add a cross-reference to the range feature as follows: database=”intact”, identifier=”EBI-xxxxxxx”, qualifier=”complex component” to identify the appropriate participant AC of the complex component

means a change to our definition of MI-JSON. (I have some other questions about the status of MI-JSON which I'll raise on the PSI-MI list.)

I'm not quite sure what to do next (we make the proposed change to our definition of MI-JSON? hack around with the JSON to see what would currently work?). I see the minutes have 'Noe and Colin to sort this out' as an action point, which I'm fine with,

best wishes,
Colin

**Comment by bmeldal** [comment]
Thanks, Colin. I'm not expecting miracles, just magic ;-)

We know that using complexes as interactors would cause issues but I guess we'll only really know about them by trying!

I'll leave you and Noe to look into it and looking forward to seeing a solution. We were discussing this again on the bus to the airport on Friday and Noe has some ideas :)

**Comment by colin-combe** [comment]
OK, works now as long as json is updated to include interactor and participant ref for features in complex that is used as participant
e.g.:
```

{
          "id": "69",
          "interactorRef": "complex portal_CPX-1919",
          "stoichiometry": "1",
          "bioRole": {
            "id": "MI:0499",
            "name": "unspecified role"
          },
          "features": [
            {
              "id": "57",
              "name": "c1s binding region",
              "category": "bindingSites",
              "type": {
                "id": "MI:0117",
                "name": "binding-associated region"
              },
              "sequenceData": [
                {
                  "pos": "?-?",
                  "interactorRef": "complex portal_CPX-1919",
                  "participantRef": "69"
                }
              ],
              "linkedFeatures": [
                "56",
                "68"
              ]
            }
          ]
        }

```
