### ISSUE TITLE
Use gene symbols a node labels

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#134]
Hi Colin,

we have user ticket:
https://github.com/Complex-Portal/complex-portal-view/issues/191
From Suzie at SGD.

**Current behaviour**

In the Participant diagram, SOME subunits are showing a PRO ID (P00410-PRO_0000006048) instead of the human readable/standard-ish name (COX2_yeast). Looks like in the righthand key, these subunits display the PRO ID instead of the UniProt accession- but clicking the PRO ID goes to UniProt anyway.

**Expected behaviour**

Subunit names in the moving diagram be uniform and recognizable by humans, eg COX2_yeast

**Minimal reproduction of the problem with instructions**

    Go to https://www.ebi.ac.uk/complexportal/complex/CPX-1721
    Look at Participants diagram

**What is the motivation / use case for changing the behaviour?**

Hard to read the diagram (minor bug as righthand list is readable)

**Please tell us about your environment:**

Mac OS 10.12.6, FF 66.
__

I thought we discussed it before as to most users the UniProt_name (= our shortlabel) or gene symbol is more human readable - but I can't find any tickets.

I think this need looking at from your side?

**Comment by colin-combe** [comment]
Hi Birgit,

I'm not sure, but I think the viewer is displaying what its asked to.

If you look at the JSON it recieves (https://www.ebi.ac.uk/intact/complex-ws/export/CPX-1721) some proteins are labelled with the "cox3_yeast" form and some with the "p00410-pro_0000006048" form.

So, assuming https://www.ebi.ac.uk/intact/complex-ws/export/CPX-1721 is displaying the JSON the viewer receives, then the problem is in that JSON?

There is a proposal for me to come down to Cambridge for a week to help with ComplexViewer issues, but I don't know when this will be.      

Colin

**Comment by bmeldal** [comment]
I know the viewer is displaying what it's supposed to as we query the "shortlabel". However, we had various discussions about displaying the "gene symbol" which is somewhere in the enriched data.

Yes, we are looking forward to hosting you for another week or 2. Just let us have the date :)

**Comment by colin-combe** [comment]
> discussions about displaying the "gene symbol" which is somewhere in the enriched data.

Um, I'm a bit confused, I don't know what the enriched data you refer to is. 

If the input JSON to ComplexViewer is searched for the the string "cox2" it doesn't appear in it - so it still seems there's not a lot ComplexViewer can do about this? (Still seems this would need fixed in the thing that produces the JSON which ComplexViewer receives?)

**Comment by bmeldal** [comment]
Ok, you are right, we do not supply the gene symbol in the JSON. In that case we need to do it in the JSON first...

In short, we can't do anything about the dodgy display when we have PRO chains. 
Ce la vie ;-)
