### ISSUE TITLE
multiple features sets

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#80]
> in the future, would it be possible to design a view where we
> could see features from more than one resource aligned to the sequence.
> For example showing variants from UniProt at the same time as a minimal
> binding region taken from MI features. Or co-displaying a minimal
> binding region with a SuperFamily or Pfam domain.

Examples: PDB tracks visible at
http://www.ebi.ac.uk/pdbe/entry/pdb/1fin/protein/2 (scroll down to 
Visualisation)

InterPro
http://www.ebi.ac.uk/interpro/protein/P06239

> Interpro is indeed very clear and intuitive! Would it work with multiple
> interactors in one graph?

With multiple interactors in one graph it might end up looking something like this:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4489277/figure/F3/

**Comment by colin-combe** [comment]
related #139

**Comment by colin-combe** [comment]
yeah... can't remember who made this comment but it does this now, see complexviewer.org.

admittedly it can get a bit noisy/garish, especially with the hatching used for uncertain features. We can see what we can do about that

@noedelta - programmatically you can still use it in the same way as the old one, see index.html for new way, lemme know if questions or problems

**Comment by bmeldal** [comment]
Hi Colin,
Thank you for working on this for a bit.

A few comments of the "garish cake slices" in collapsed view:
- The stripy protein circles take a bit getting used to but I think that's because we are so used to the "cake slices".

- When we have more than one defined region, eg in Mitochondrial pyruvate dehydrogenase or shelterin, it looks a bit odd now, with partial "slices", i.e. slices not reaching from periphery to centre point. I think the full slices relative to the size of the region worked better if there is no feature with "unknown region". I don't know how easy it would be to change.

Birgit

**Comment by colin-combe** [comment]
> it looks a bit odd now

as it is at the moment, it does look a bit odd

i plan to do something like you suggest - tidy this up by only putting annotations in a new 'track' / level if they overlap with another annotation. (applies to both bars or circles)

so, yes, i think this is something to change before deploying it

**Comment by colin-combe** [comment]
@bmeldal - see complexviewer.org for way it works now, what do you think?
if you enable all or most of the annotation sets (uniprot, superfam, etc) its kind of inevitable that its going to get too busy

it should be that if it can display the pie slices in a simple way (like the old way) then it does

i think diagonal hatches for uncertain bits of features and the 'concentric pie slices' for overlapping features are the most consistent way to display things; even though both these things contribute to it looking more hectic

**Comment by bmeldal** [comment]
Ok, that looks good!

I'm getting used to the hatched areas.
